#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Crossbill plugin release signing key"

# ── Stage 1: prerequisites ────────────────────────────────────────────────
stage "Check the tools"
say "Signing needs OpenSSL with Ed25519 support and an authenticated gh."
MISSING=0
if openssl genpkey -algorithm ed25519 -out /dev/null 2>/dev/null; then
  say "openssl: Ed25519 supported"
else
  warn "openssl cannot generate Ed25519 keys. Install OpenSSL 1.1.1 or newer."
  MISSING=1
fi
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "gh: authenticated"
else
  warn "gh is missing or not logged in. Run: gh auth login"
  MISSING=1
fi
if [[ "$MISSING" -ne 0 ]]; then
  warn "Fix the above, then run this wizard again."
  exit 1
fi
pause "Both tools are ready. Press Enter to continue."

# ── Stage 2: generate the keypair ─────────────────────────────────────────
stage "Generate the signing key"
say "The private key signs every release. It must never enter this repository."
say "The default location is outside the repo, in your home directory."
ask CROSSBILL_SIGNING_KEY_PATH "Where should the private key live? [$HOME/.crossbill/signing.pem]"
[[ -z "$CROSSBILL_SIGNING_KEY_PATH" ]] && CROSSBILL_SIGNING_KEY_PATH="$HOME/.crossbill/signing.pem"

if [[ -f "$CROSSBILL_SIGNING_KEY_PATH" ]]; then
  say "A key already exists at that path, so it is kept."
  warn "Generating a new one would strand every reader running a published version."
else
  mkdir -p "$(dirname "$CROSSBILL_SIGNING_KEY_PATH")"
  openssl genpkey -algorithm ed25519 -out "$CROSSBILL_SIGNING_KEY_PATH"
  chmod 600 "$CROSSBILL_SIGNING_KEY_PATH"
  printf '  %s✓ generated%s %s\n' "$GREEN" "$RESET" "$CROSSBILL_SIGNING_KEY_PATH"
fi
write_env CROSSBILL_SIGNING_KEY_PATH "$CROSSBILL_SIGNING_KEY_PATH"
pause "Press Enter to continue."

# ── Stage 3: back it up ───────────────────────────────────────────────────
stage "Back up the private key"
warn "Lose this key and you cannot publish an update any reader can install."
say "Copy the whole block below into your password manager now:"
printf '\n'
cat "$CROSSBILL_SIGNING_KEY_PATH"
printf '\n'
until confirm "Have you stored the private key somewhere safe?"; do
  say "Take your time. The rest of the setup is pointless without a backup."
done

# ── Stage 4: give it to CI ────────────────────────────────────────────────
stage "Set the GitHub Actions secret"
say "The Release workflow reads the key from a secret named CROSSBILL_SIGNING_KEY."
set_secret CROSSBILL_SIGNING_KEY "$(cat "$CROSSBILL_SIGNING_KEY_PATH")"
open_url "https://github.com/Crossbill-App/koreader-plugin/settings/secrets/actions"
step "Confirm CROSSBILL_SIGNING_KEY is listed on that page."
pause "Press Enter once you have checked."

# ── Stage 5: the public key ───────────────────────────────────────────────
stage "Publish the public key"
CROSSBILL_SIGNING_PUBKEY=$(openssl pkey -in "$CROSSBILL_SIGNING_KEY_PATH" -pubout -outform DER | tail -c 32 | xxd -p -c 32)
say "This is the public half. It is not secret; it belongs in the repository."
printf '\n  %s%s%s\n\n' "$BOLD" "$CROSSBILL_SIGNING_PUBKEY" "$RESET"
write_env CROSSBILL_SIGNING_PUBKEY "$CROSSBILL_SIGNING_PUBKEY"
step "Open crossbill.koplugin/modules/update/keys.lua"
step "Paste the hex above as the newest entry in the trusted key list."
step "Leave the older entries in place, or readers on an older plugin cannot update."
say "Then commit that file. The Release workflow checks its own signature"
say "against it, so a mismatch fails the release instead of shipping."
pause "Press Enter to finish."

finish
